spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eschool
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect